### ISSUE TITLE
dockerhub error during pull

### ISSUE THREAD

**Issue by NetSolutionArchitect** [crazy-max/docker-artifactory#3]
When pulling (docker pull crazymax/artifactory), error occurs: manifest for crazymax/artifactory:latest not found: manifest unknown: manifest unknown.

Would you be so kind and alter/create manifest, so that it would be possible to use the image?

Thanks in advance.

**Comment by crazy-max** [comment]
@NetSolutionArchitect There is no `latest` tag because this repo handles multi images as specified in the README:

* `crazymax/artifactory:oss-latest`
* `crazymax/artifactory:pro-latest`
* `crazymax/artifactory:nginx-pro-latest`
